# sqliteondbf
language: python

python:
  - "3.5"

cache: pip

# command to run tests and install dependencies
install:
  # for coverage
  - pip install codecov
  - pip install pytest-cov
  # dependencies
  - pip install -e .

# script
script:
  - py.test --cov=sqliteondbf test

after_success:
  - codecov
